kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Values.name }}-service"
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: 80
      targetPort: 5140
