apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-route
  name: istio-system
spec:
  hosts:
    - ielsapi.sudhansunayak.com
  gateways:
    - ext-host-gwy
  http:
    - route:
        - destination:
            host: dotnettestapi-service.develop.svc.cluster.local
